In [2]:
import numpy

In [3]:
numbers = numpy.array([1,2,3,4,5])

In [4]:
import numpy as np

In [5]:
numbers = np.array([1,2,3,4,5])

In [6]:
print(numbers)
print(type(numbers))
print(numbers.ndim)
print(numbers.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [7]:
numbers = np.array([ [1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5] ]
                   )

In [8]:
print(numbers)
print(type(numbers))
print(numbers.ndim)
print(numbers.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
2
(3, 5)


In [9]:
numbers[0][1]

2

In [10]:
numbers = np.array( [
                  [ [1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5] ],
                  [ [1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5] ] ,
                  [ [1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5] ]  ]
                   )

In [11]:
numbers[0][1][4]

5

In [12]:
print(numbers)
print(type(numbers))
print(numbers.ndim)
print(numbers.shape)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
<class 'numpy.ndarray'>
3
(3, 3, 5)


In [13]:
print(numbers.dtype)

int64


In [14]:
print(numbers.size)

45


In [15]:
print(numbers.itemsize)

8


In [16]:
ary = np.array([[1,2,3], [4,5,6]], dtype=np.float64)

In [17]:
print(ary)

[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
ary = np.array([[1,2,3], [4,5,6]], dtype=np.int32)

In [19]:
print(ary)

[[1 2 3]
 [4 5 6]]


In [20]:
ary>5

array([[False, False, False],
       [False, False,  True]])

In [21]:
ary[ary>5]

array([6], dtype=int32)

In [22]:
ary<=5

array([[ True,  True,  True],
       [ True,  True, False]])

In [23]:
ary[ary<=5]

array([1, 2, 3, 4, 5], dtype=int32)

In [24]:
ary==5

array([[False, False, False],
       [False,  True, False]])

In [25]:
ary[ary==5]

array([5], dtype=int32)

In [26]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [27]:
print(grades)
print(grades.ndim)

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
2


In [28]:
grades.max()

100

In [29]:
grades.min()

70

In [30]:
grades.sum()

1054

In [31]:
grades.std()

8.792357792739987

In [32]:
grades.mean()

87.83333333333333

In [33]:
grades.var()

77.30555555555556

In [34]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [35]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [36]:
grades.mean(axis=1).std()

2.8819360776317633

In [37]:
num1 = np.arange(1,6,2)
print(num1)

[1 3 5]


In [38]:
num1 = np.arange(1,6)
print(num1)

[1 2 3 4 5]


In [39]:
num2 = num1
num2[1] = 50
print(num1)
print(num2)

[ 1 50  3  4  5]
[ 1 50  3  4  5]


In [40]:
num2 = num1.view()
num2[1] = 100
print(num1)
print(num2)

[  1 100   3   4   5]
[  1 100   3   4   5]


In [41]:
num1 = np.arange(1,6)
print(num1)

[1 2 3 4 5]


In [42]:
num2 = num1.copy()
num2[1] = 100
print(num1)
print(num2)

[1 2 3 4 5]
[  1 100   3   4   5]


In [43]:
num1 = np.array([5,8,15,25])
num1

array([ 5,  8, 15, 25])

In [44]:
num2 = np.arange(1,5)*5

In [45]:
np.add(num1, num2)

array([10, 18, 30, 45])

In [46]:
num1+num2

array([10, 18, 30, 45])

In [47]:
np.sqrt(num2)

array([2.23606798, 3.16227766, 3.87298335, 4.47213595])

In [48]:
np.exp(num2)

array([1.48413159e+02, 2.20264658e+04, 3.26901737e+06, 4.85165195e+08])

In [49]:
np.power(num2,2)

array([ 25, 100, 225, 400])

In [50]:
np.log10(num2)

array([0.69897   , 1.        , 1.17609126, 1.30103   ])

In [51]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [52]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [53]:
np.linspace(0,30,11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [54]:
numbers = np.arange(1,11)

In [55]:
numbers[1:4]

array([2, 3, 4])

In [56]:
numbers[:4]

array([1, 2, 3, 4])

In [57]:
numbers[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
numbers[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
numbers[1:6:2]

array([2, 4, 6])

In [60]:
numbers[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [61]:
num = np.array([ [1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5] ]
                   )

In [62]:
num[1:3]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [63]:
grades = np.array([[87, 96, 70],
 [100, 87, 90],
  [94, 77, 90],
   [100, 81, 82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [64]:
grades[1]

array([100,  87,  90])

In [65]:
grades[1][2]

90

In [66]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [67]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [68]:
grades[[0,3]]

array([[ 87,  96,  70],
       [100,  81,  82]])

In [69]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [70]:
grades[:, 1]

array([96, 87, 77, 81])

In [71]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [72]:
grades[:, [0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [73]:
number = np.arange(6)
print(number)
print(number.shape)

[0 1 2 3 4 5]
(6,)


In [74]:
number = number.reshape((3,2))

In [75]:
print(number)

[[0 1]
 [2 3]
 [4 5]]


In [76]:
print(number.shape)

(3, 2)


In [77]:
number = number.reshape((5,2)) # ERROR

ValueError: cannot reshape array of size 6 into shape (5,2)

In [78]:
number = np.arange(0,9).reshape((3,3))
print(number)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
number.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [80]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [82]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [89]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 2 3]
 [4 5 6]]


In [90]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [92]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [93]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [96]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [97]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [98]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [99]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [100]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [103]:
from numpy import random

x = random.rand(5)

print(x)

[0.10148519 0.6532204  0.465747   0.39933156 0.1111788 ]


In [104]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[15 76 97 36 83]


In [105]:
x=random.randint(100, size=(5,5))

print(x)

[[65 85 28 52 12]
 [68  3 43 22 64]
 [24 51 99 90 59]
 [71 69 50 21 30]
 [26 89 79 58 57]]


In [106]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [107]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 7 5 9]
 [3 3 3 5 7]
 [7 7 7 5 3]]
