In [68]:
import numpy as np 
array = np.array([1,2,3,4])

print(array)

[1 2 3 4]


In [71]:
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [72]:
array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [81]:
output = np.array([[x for x in range(2,22,2)],[x for x in range(1,21,2)]])
output

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [88]:
ary = np.array([[1,2,3],[4,5,6]])
ary
ary.ndim
ary.dtype
ary.size
ary.itemsize
ary.shape


(2, 3)

Array Operation

In [92]:
ary = np.array([[12,32,42],[41,76,85]])
ary>69
ary<69
ary >= 42
arr1 = ary <= 41
print(arr1)


[[ True  True False]
 [ True False False]]


In [93]:
arr = ary[ary>69]
arr

array([76, 85])

Numpy Methods

In [110]:
grades = np.array([[67,87,56,90],[98,87,88,78],[90,85,78,81],[100,96,89,72]])

print(grades)
grades.shape
grades.max(axis = 1)
grades.min()
grades.sum()
grades.mean()
grades.var()
grades.std()
grades.mean(axis = 0 )
grades.mean(axis = 1)

[[ 67  87  56  90]
 [ 98  87  88  78]
 [ 90  85  78  81]
 [100  96  89  72]]


array([75.  , 87.75, 83.5 , 89.25])

Shallow Copy

In [113]:
array1 = np.array([1,2,3,4])
array1
array2 = array1
array2
array2[2] = 69
array1

array([ 1,  2, 69,  4])

Deep Copy

In [118]:
array1 = np.array([1,2,3,4])
array1
array2 = array1.copy()
array2
array2[1] = 69
print(array1)
print(array2)

[1 2 3 4]
[ 1 69  3  4]


Arithmetic Function

In [129]:
arr1 = np.array([5,8,16,25])
arr1
arr2 = np.arange(1,5) *5
arr2
 # [5,10,15,20]
np.add(arr1,arr2)
np.subtract(arr1,arr2)
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.sqrt(arr1)

array([2.23606798, 2.82842712, 4.        , 5.        ])

Exponents and logarithms


In [136]:
arr = np.arange(1,4)*3
arr
#[3,6,9]

np.exp(arr)
np.power(arr,2)
np.log(arr)

array([1.09861229, 1.79175947, 2.19722458])

Trigonometric

In [67]:
theta = np.pi

np.sin(theta)
np.cos(theta)
np.tan(theta)

np.arcsin(1)
np.arccos(1)
np.arctan(1)



array([ 90., 180., 270., 360.])

Indexing and Slicing

In [148]:
grades = np.array([[87, 96, 70],
 [100, 87, 90],
  [94, 77, 90],
   [100, 81, 82]])

grades[0, :]
grades[:, 0]

array([ 87, 100,  94, 100])

Exercise

In [141]:
arr = np.array([[[1, 3, 2,4],[8, 6, 5,7],[11,10,12,9]]])
arr.shape
print(arr.transpose())


[[[ 1]
  [ 8]
  [11]]

 [[ 3]
  [ 6]
  [10]]

 [[ 2]
  [ 5]
  [12]]

 [[ 4]
  [ 7]
  [ 9]]]


In [142]:
arr.reshape(4,3)

array([[ 1,  3,  2],
       [ 4,  8,  6],
       [ 5,  7, 11],
       [10, 12,  9]])

In [147]:
np.sort(arr)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])